name: env-hpc

channels:
  - conda-forge
  - williamfgc

dependencies:
  - python3
  - mpi4py 
  - matplotlib
  - numpy
  - openmpi
  - mpi4py
  - cython
  - cffi
  - numexpr
  - pandas
  - dask
  - snakeviz
